id: I99EFEDB8
ocr_import_info:
  timestamp: '2023-08-21T07:20:12.630840+00:00'
  batch_id: batch-37ad
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-08-21 08:54:47.251637+00:00
last_modified: 2023-08-21 08:54:47.251646+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG22350
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG22350
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་འཇུག་པའི་རྩ་བའི་སྦྱོར་ཊིཀ་དང་ས་བཅད།
  languages:
  - en
  - bo
  author: མཁན་པོ་སངས་རྒྱས་བསྟན་འཛིན།
statistics:
  ocr_word_mean_confidence_index: 0.9821032837639516
  ocr_word_median_confidence_index: 0.99999845
bases:
  I1KG22371:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22371
      total_pages: 342
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22371.txt
    statistics:
      ocr_word_median_confidence_index: 0.99999845
      ocr_word_mean_confidence_index: 0.9821032837639516
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
